/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Fri Feb  9 18:37:44 2024


#include "GoogleSpeechTranscription_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(GoogleSpeechTranscriptionParamsCOMPONENT, "yarp.device.GoogleSpeechTranscription")
}


std::vector<std::string> GoogleSpeechTranscription_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("language_code");
    params.push_back("sample_rate_hertz");
    return params;
}


bool      GoogleSpeechTranscription_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(GoogleSpeechTranscriptionParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter language_code
    {
        if (config.check("language_code"))
        {
            m_language_code = config.find("language_code").asString();
            yCInfo(GoogleSpeechTranscriptionParamsCOMPONENT) << "Parameter 'language_code' using value:" << m_language_code;
        }
        else
        {
            yCError(GoogleSpeechTranscriptionParamsCOMPONENT) << "Mandatory parameter 'language_code' not found!";
            yCError(GoogleSpeechTranscriptionParamsCOMPONENT) << "Description of the parameter: Language for speech synthesis (e.g. \"ita\", \"eng\")";
            return false;
        }
        prop_check.unput("language_code");
    }

    //Parser of parameter sample_rate_hertz
    {
        if (config.check("sample_rate_hertz"))
        {
            m_sample_rate_hertz = config.find("sample_rate_hertz").asInt64();
            yCInfo(GoogleSpeechTranscriptionParamsCOMPONENT) << "Parameter 'sample_rate_hertz' using value:" << m_sample_rate_hertz;
        }
        else
        {
            yCInfo(GoogleSpeechTranscriptionParamsCOMPONENT) << "Parameter 'sample_rate_hertz' using DEFAULT value:" << m_sample_rate_hertz;
        }
        prop_check.unput("sample_rate_hertz");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(GoogleSpeechTranscriptionParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(GoogleSpeechTranscriptionParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      GoogleSpeechTranscription_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: GoogleSpeechTranscription\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'language_code': Language for speech synthesis (e.g. \"ita\", \"eng\")\n");
    doc = doc + std::string("'sample_rate_hertz': The input audio sample rate\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device GoogleSpeechTranscription --language_code <mandatory_value> --sample_rate_hertz 16000\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device GoogleSpeechTranscription --language_code <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
